### ISSUE TITLE
Move doc from Sanger Wiki to this repo

### ISSUE THREAD

**Issue by flass** [johnlees/bioinformatics#2]
Hi John,

we're migrating the Internal Sanger Wiki as it is soon to be defunct, and i found a page that seems would be more appropriately hosted in this repo as the README or something close:
http://mediawiki.internal.sanger.ac.uk/index.php/Jl11_scripts

would you mind taking the info and porting it over? 
We have a script to convert the Wiki content into Confluence Wiki Markdown, but not into GitHub markdown I'm afraid; however if you find this useful I'm happy to provide the converted content.

best,

Florent

**Comment by johnlees** [comment]
Yeah I can try and do that, if you send me the markdown you can generate I'll take it from there

**Comment by flass** [comment]
OK, see attached - I did some cleaning work so it looks more like GitHub stuff than like Confluence, but prob still need cleaning to work.
[Jl11_scripts.md](https://github.com/johnlees/bioinformatics/files/9647976/Jl11_scripts.md)
